### ISSUE TITLE
you stole this idea from other guy

### ISSUE THREAD

**Issue by amongussusususu** [quintindunn/JKLMWordTester#1]
omggggggggggggggg

**Comment by quintindunn** [comment]
I don't understand what your point is? Just because someone has made a project before doesn't mean I can't write my own version? I created mine completely from scratch, interpreting the web-socket data by myself, doing everything by myself. Did the original developers of Google steal the idea of a search engine? No, they created their own version, then expanded on it. I would greatly appreciate if you could direct me to who I "stole" this from. 

Thank you,
Quintin
